name: Enhanced LinkedIn Automation

on:
  schedule:
    # Send 3 times daily to Telegram: 9 AM, 12 PM, 4 PM IST
    # IST is UTC+5:30, so we need to subtract 5:30 from IST times
    - cron: '30 3 * * *'   # 9:00 AM IST (3:30 AM UTC)
    - cron: '30 6 * * *'   # 12:00 PM IST (6:30 AM UTC)  
    - cron: '30 10 * * *'  # 4:00 PM IST (10:30 AM UTC)
  
  workflow_dispatch: # Allows manual triggering

jobs:
  linkedin-automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests feedparser python-dotenv Pillow google-generativeai beautifulsoup4
        
    - name: Diagnose environment
      run: |
        python diagnose_env.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        
    - name: Generate and send LinkedIn content
      run: |
        python main.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        
    - name: Upload generated images
      uses: actions/upload-artifact@v4
      with:
        name: linkedin-content-${{ github.run_number }}
        path: generated_images/
        retention-days: 7
      if: always() && hashFiles('generated_images/**') != ''
