name: Auto WhatsApp LinkedIn Content

on:
  schedule:
    # Send content 3 times daily: 9 AM, 2 PM, 6 PM UTC
    - cron: '0 9 * * *'   # 9:00 AM UTC (2:30 PM IST)
    - cron: '0 14 * * *'  # 2:00 PM UTC (7:30 PM IST)  
    - cron: '0 18 * * *'  # 6:00 PM UTC (11:30 PM IST)
  
  workflow_dispatch:
    inputs:
      message:
        description: 'Custom message to add'
        required: false
        default: ''

jobs:
  send-whatsapp-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser python-dotenv
        
    - name: Generate WhatsApp content
      run: |
        python whatsapp_content_generator.py
      env:
        WHATSAPP_PHONE: ${{ secrets.WHATSAPP_PHONE }}
        
    - name: Upload WhatsApp content
      uses: actions/upload-artifact@v4
      with:
        name: whatsapp-linkedin-content-${{ github.run_number }}
        path: |
          whatsapp_content/
          generated_images/
        retention-days: 7